//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaGH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string cedula { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public System.DateTime fecha_nac { get; set; }
        public string sucursal { get; set; }
        public string parte_atras { get; set; }
        public string ocupacion { get; set; }
        public decimal sueldo_bruto { get; set; }
        public decimal horas_extras { get; set; }
        public decimal seguro_privado { get; set; }
        public decimal san_mayo { get; set; }
        public bool comida { get; set; }
        public System.DateTime fecha_entrada { get; set; }
        public string fecha_salida { get; set; }
        public bool actual { get; set; }
    }
}
