//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaGH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resultados
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string cedula { get; set; }
        public string ocupacion { get; set; }
        public string sucursal { get; set; }
        public string sucursal2 { get; set; }
        public decimal sueldo_bruto { get; set; }
        public decimal horas_extras { get; set; }
        public decimal neto_apagar { get; set; }
        public decimal afp { get; set; }
        public decimal sfs { get; set; }
        public decimal seguro { get; set; }
        public decimal isr { get; set; }
        public decimal total_decuento { get; set; }
        public decimal neto_apagar2 { get; set; }
        public decimal comida { get; set; }
        public decimal prestamo { get; set; }
        public decimal san_mayo { get; set; }
        public decimal desayuno { get; set; }
        public decimal otros { get; set; }
        public decimal total_descuento2 { get; set; }
        public decimal neto_apagar3 { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
